//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("BioData")]
    public partial class BioData
    {
        [Key]
        public long BioDataID { get; set; }
        public int SessionID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> HR { get; set; }
        public Nullable<double> SC { get; set; }
        public Nullable<double> AccX { get; set; }
        public Nullable<double> AccY { get; set; }
        public Nullable<double> AccZ { get; set; }
    
        public virtual Sessions Sessions { get; set; }
    }
}
