//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TradingData")]
    public partial class TradingData
    {
        [Key]
        public long TradeID { get; set; }
        public int SessionID { get; set; }
        public string Symbol { get; set; }
        public System.DateTime OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public decimal OpenPrice { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<decimal> ProfitLoss { get; set; }
        public string Action { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Sessions Sessions { get; set; }
    }
}
