//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("Server=185.144.156.161;Database=nt;User Id=neurouser;Password = AlggoMalgo123;")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           // throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BioData> BioData { get; set; }
        public virtual DbSet<PriceData> PriceData { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<TradingData> TradingData { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
