//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PriceData
    {
        [Key]
        public long PriceID { get; set; }
        public int SessionID { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<decimal> HighPrice { get; set; }
        public Nullable<decimal> LowPrice { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<decimal> PriceAsk { get; set; }
        public Nullable<decimal> PriceBid { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string TimeFrame { get; set; }
    
        public virtual Sessions Sessions { get; set; }
    }
}
