//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sessions()
        {
            this.BioData = new HashSet<BioData>();
            this.PriceData = new HashSet<PriceData>();
            this.TradingData = new HashSet<TradingData>();
        }

        [Key]
        public int SessionID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime LoginTimeLocal { get; set; }
        public System.DateTime LoginTimeUniversal { get; set; }
        public Nullable<System.DateTime> LogoutTimeLocal { get; set; }
        public Nullable<System.DateTime> LogOutTimeUniversal { get; set; }
        public string IP { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string OS { get; set; }
        public string LocalTimeZone { get; set; }
        public string ScreenResolution { get; set; }
        public string AddtitionalInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BioData> BioData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceData> PriceData { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingData> TradingData { get; set; }
    }
}
